
sonar.projectKey=GabCresc_TheWorldSerpentInn_project
sonar.organization=gabcresc
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources = src
sonar.java.binaries=target/classes
sonar.java.libraries=lib/**/*.jar
# Escludi le immagini e i file multimediali dall'analisi del codice
sonar.exclusions=**/*.jpg, **/*.jpeg, **/*.png, **/*.gif, **/*.bmp, **/*.ico, src/main/resources/client_secret.json
sonar.coverage.exclusions=**/*

