sonar.projectKey=GabCresc_TheWorldSerpentInn_project
sonar.organization=gabcresc
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Escludi le immagini e i file multimediali dall'analisi del codice
sonar.exclusions=**/*.jpg, **/*.jpeg, **/*.png, **/*.gif, **/*.bmp, **/*.ico
